### ISSUE TITLE
Filters not working in TYPO3 10.4.8

### ISSUE THREAD

**Issue by web2date** [PIT-Solutions-Private-Limited/pits_downloadcenter#4]
Installation: TYPO3 10.4.8, Bootstrap Package 11.1.0-dev

Hi, thanks for this nice Extension...but I cannot get this extension working on both filters...
Keywordsearch is okay - but **filters show zero results**. Of course everything is added correctly in fileadmin storage folder.

![image](https://user-images.githubusercontent.com/8898397/93860032-b6423700-fcbe-11ea-8008-e393b6bf30f9.png)
![image](https://user-images.githubusercontent.com/8898397/93860091-d3770580-fcbe-11ea-9a29-dece42ddf1c4.png)
![image](https://user-images.githubusercontent.com/8898397/93860174-f6a1b500-fcbe-11ea-9e4a-70fdf57e5cd7.png)

Is it a bug or a misconfiguration on my part?

**Comment by SruthiKumar333** [comment]
Dear @web2date ,
 This seems to be a misconfiguration in the storage folder. Make sure you are editing the files in the storage folder, specifically created for Download center extension. I suppose you are editing files in the base path (folder in the auto-created fileadmin). Also check the are linked to corresponding category and filetype records there.
![stoargeFolder](https://user-images.githubusercontent.com/53466587/93872767-45b30e80-fcee-11ea-826c-00e0ba69d4f3.png)

**Comment by web2date** [comment]
Hi @SruthiKumar333 
Thanks for your quick answer...now its working...
